name: Document publish
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Install and Build 🔧
        run: |
          yarn
          yarn docs:build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: docs
          folder: doc-dist
